services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  mathbuddy-web:
    image: dhan007/mathbuddy:latest
    entrypoint: "./entrypoint.sh"
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes: 
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=mathbuddy.settings.prod
      - POSTGRES_DB=mathbuddy
      - POSTGRES_USER=mathbuddy
      - POSTGRES_PASSWORD=mathbuddy
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"